# Generated by Django 4.1.5 on 2023-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.JSONField(null=True),
        ),
    ]
