# Generated by Django 4.1.5 on 2023-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_task_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
