# Generated by Django 4.1.5 on 2023-02-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0003_alter_task_endtime_alter_task_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='bed_time',
            field=models.TimeField(),
        ),
    ]
