# Generated by Django 4.1.5 on 2023-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0004_alter_routine_bed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='task_count',
            field=models.IntegerField(null=True),
        ),
    ]
